variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonar

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

sonar:
  image: gradle:8.10.1-eclipse-temurin-17
  script:
    - ./gradlew sonarqube
      -Dsonar.projectKey=FitQuest
      -Dsonar.host.url=http://localhost:9000
      -Dsonar.login=admin
      -Dsonar.password=Bogdan.01071980