image: gradle:8.2.0-jdk17-jammy

variables:
  GIT_DEPTH: "0"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube-check

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew clean test jacocoTestReport

sonarqube-check:
  stage: sonarqube-check
  script:
    ./gradlew sonar "-Dsonar.token=SONAR_TOKEN"
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
