image: gradle:8.2.0-jdk17-jammy

variables:
  GIT_DEPTH: "0"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube-check
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew clean test jacocoTestReport

sonarqube-check:
  stage: sonarqube-check
  script:
    - ./gradlew clean build
    - ./gradlew sonar "-Dsonar.token=$SONAR_TOKEN" "-Dsonar.java.binaries=build/classes/java/main"
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    - ./gradlew assemble
    - docker build -t fitquest .
    - docker stop fitquest-app_staging || true
    - docker rm fitquest-app_staging || true
    - docker run -d -p 8090:8080 --net=fitquest-network --env spring_profiles_active=docker --name=fitquest-app_staging fitquest
  only:
    - master
    - main