version: '3.8'

services:
  fitquest_sql:
    image: mysql
    container_name: fitquest_sql
    environment:
      MYSQL_DATABASE: fitquest_db
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - fitquest-network

  fitquest_sql_staging:
    image: mysql
    container_name: fitquest_sql_staging
    environment:
      MYSQL_DATABASE: fitquest_db
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3390:3306"
    networks:
      - fitquest-network

  fitquest-app:
    image: fitquest
    container_name: fitquest-app
    build:
      context: .
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - fitquest-network

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - fitquest-network

volumes:
  mysql_data:

networks:
  fitquest-network:
    name: fitquest-network
    driver: bridge