version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fitquest-app:latest
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fitquest-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fitquest_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: fitquest_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fitquest-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - fitquest-network

volumes:
  mysql_data:

networks:
  fitquest-network:
    driver: bridge